import AppShell from '@/components/appshell';
import Stepper from '@/components/stepper';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function OfferLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <AppShell>
            <div className='flex h-full w-full flex-col items-center gap-8 overflow-hidden rounded-xl bg-background p-10'>
                <Stepper />
                {children}
            </div>
        </AppShell>
    );
}
