import AppShell from '@/components/appshell'
import Stepper from '@/components/stepper'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function OfferLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AppShell>
      <div className="flex flex-col items-center gap-8 rounded-xl bg-background overflow-hidden w-full h-full p-10">
          <Stepper/>
        {children} 
      </div>
    </AppShell>
  )
}
