import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import './globals.css';
import CookieBar from '@/components/cookiebar';

const inter = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en'>
            <CookieBar />
            <body className={inter.className}>
                <div className='flex items-center justify-center w-full h-full'>
                    {children}
                </div>
            </body>
        </html>
    );
}
