import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function OfferLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return <div className='relative flex w-full h-full items-center justify-center'>{children}</div>;
}
