import Graph from "@/components/chart";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import Stepper from "@/components/stepper";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import Image from "next/image";
import Link from "next/link";

const YourOffer = () => {

    return (
        <>
        <main className={`relative flex justify-center items-center w-full min-h-screen bg-center px-12 py-16 flex-col`}>
            <div className="fixed inset-0 -z-10 w-screen h-full">
                <Image fill src={'/images/image-10.jpg'} alt="Hero Image"/>
            </div>
            <Navbar className="absolute"/>
            <div className="px-4 py-6 flex justify-between items-center bg-[#E7F5FA] w-full rounded-t-md">
                <div className="flex gap-4 font-medium">
                    <span>5 Panels €3,600</span>
                    <span>Average Savings €600/year</span>
                </div>
                <Button asChild>
                    <Link href={'/contactdetails'}>
                        Sign Contract
                    </Link>
                </Button>
            </div>
            <div className="flex flex-col items-center gap-8 rounded-xl rounded-t-none bg-background overflow-hidden w-full h-full p-10">
                <Stepper/>
                <div className="flex w-full items-center justify-between">
                    <div className="flex flex-col w-1/2 items-center justify-center gap-2">
                        <div className="relative w-full max-w-[436px] aspect-[436/490]">
                            <Image src={`/images/image-11.png`} alt="Solar Panel" fill/>
                        </div>
                        <div className="flex flex-col items-center gap-1">
                            <h1 className="text-2xl font-bold">€3,600</h1>
                            <p className="text-gray">for 25 years of solar power</p>
                        </div>
                    </div>
                    <div className="flex flex-col gap-4">
                        <div className="flex flex-col gap-1 ">
                            <h1 className="font-bold text-3xl">Your Offer</h1>
                            <p className="font-medium text-gray text-base">{`5 Panels (Equivalent to 3.2KWp)`}</p>
                        </div>
                        <ul className="flex flex-col gap-2 text-base">
                            <li>{`• €600 yearly savings (€15,000 total savings)`}</li>
                            <li>{`• 4.5 years payback`}</li>
                            <li>{`• 65% of consumption covered by solar`}</li>
                        </ul>
                        <Button className="self-start">DOWNLOAD OFFER</Button>
                    </div>
                </div>
                <div className="flex gap-8 items-center border p-4 rounded-3xl self-end">
                    <span className="inline-flex font-medium">Licensed&nbsp;by</span>
                    <div className="flex gap-2 w-full items-center">
                            <Image src={'/images/cnmc.png'} alt="cnmc" className="w-[55px] h-[30px]" width={55} height={30}/>
                            <Image src={'/images/omie-removebg-preview.png'} alt="cnmc" className="w-[62px] h-[30px]" width={62} height={30}/>
                            <Image src={'/images/ree-removebg-preview.png'} alt="cnmc" className="w-[136px] h-[17px]" width={136} height={17}/>
                    </div>
                </div>
                <div className="flex w-full gap-4">
                    <div className="w-1/2 flex flex-col gap-8 border rounded-3xl px-4 py-8 pl-8">
                        <h2 className="text-center font-bold text-xl">How It Works?</h2>
                        <ul className="flex flex-col gap-4 list-disc">
                            <li>Neos becomes your retailer and uses the grid system to transport the electricity generated by your solar panels into your  home.</li>
                            <li>During solar production hours, you will pay €0.00 for the energy you consume.</li>
                            <li>If there is excess production, Neos will sell 100% of the excess to the electricity market.</li>
                            <li>Outside of solar production hours you will pay the market price of electricity, with a margin of €0.01 per KWh.</li>
                            <li>You will need to pay tolls and costs associated with using the grid, estimated at €0.02 per KWh.</li>
                            <li>If you decide you do not want Neos as your retailer, there is no commitment to stay with us, and you can choose another retailer at any point.</li>
                            <li>If you choose another retailer, we will send you every month the revenues generated by selling your solar energy into the electricity market, which is equivalent to the savings you would obtain if you were still with Neos.</li>
                        </ul>
                    </div>
                    <div className="w-1/2 flex flex-col gap-4">
                        <div className="flex flex-col gap-8 border rounded-3xl px-4 py-8 pl-8">
                            <h2 className="text-center font-bold text-xl">Compare Our Offer</h2>
                            <ul className="flex flex-col gap-4 list-disc">
                                <li>35% cheaper than rooftop solar panels</li>
                                <li>40% more energy production per panel compared to rooftop solar panels</li>
                                <li>85% savings compared to traditional utility providers</li>
                                <li>80% less carbon intensive than traditional utility providers</li>
                            </ul>
                        </div>
                        <div className="bg-[#E7F5FA] border rounded-3xl px-4 py-8 flex flex-col gap-5 items-center justify-center h-full">
                            <div className="font-semibold text-lg text-center">Review your proposal with your Solar Expert</div>
                            <Avatar className="w-[50px] h-[50px] rounded-full">
                                <AvatarImage src="/images/person.png" />
                                <AvatarFallback>CN</AvatarFallback>
                            </Avatar>
                            <div className="flex flex-col justify-center items-center">
                                <span className="text-sm font-medium">Sebastian Gonzalez</span>
                                <span className="text-sm text-gray">sebastian@solarmente.se</span>
                            </div>
                            <Button>TALK TO YOUE EXPERT</Button>
                        </div>
                    </div>
                </div>
                <div className="border w-full rounded-3xl overflow-hidden">
                    <div className="flex justify-between pt-4 px-4 items-center">
                        <div className="font-medium text-xl">Simulation</div>
                        <div className="flex gap-4">
                            <div className="flex gap-1 items-center">
                                <span className="w-6 h-3 bg-[#436DC6]"></span>
                                <span>Product 1</span>
                            </div>
                            <div className="flex gap-1 items-center">
                                <span className="w-6 h-3 bg-[#3492AC]"></span>
                                <span>Product 2</span>
                            </div>
                        </div>
                    </div>
                    <Graph/>
                </div>
            </div>
            <Footer className="absolute bottom-0"/>
        </main>
        </>
    );
}

export default YourOffer;